### ISSUE TITLE
Test analysis for (unit) tests cg analysis

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/trailblazer#44] opened 2019-02-13 11:47 UTC
Problem description: 
We do not have any CLI tests for cg analysis and we need that to make development safe.

Suggested solution:
We need add tests for:

cg analysis link
cg analysis config
cg analysis panel
cg analysis start
cg analysis -f
cg analysis auto
cg analysis remove_fastq
To think about for each unit test:

Requirements: pass/not pass, paths/decisions taken in the code
Exit conditions (when can you stop testing?):
Input/output:

In this user story we will analyze the points above and come up with a test plan (sort of a test spec).

Q: Where and in what format should we have the test plan? 
A: In a GitHub issue, in cg repo.
Q: One plan for each unit?
A: No, one plan to cover all these units.

DoD:
A test plan is in place.

How to Demo:
Show the plan.

**Comment by b4ckm4n** [comment] 2019-03-13 12:35
Wow this was cool, should we add this to the Development Manual?

**Comment by ingkebil** [comment] 2019-03-27 21:03
Looks like a duplicate of https://github.com/Clinical-Genomics/cg/issues/256

**Comment by patrikgrenfeldt** [comment] 2019-04-09 08:34
closing duplicate!

**Closed** 2020-08-28 09:43 UTC
Labels: PBL Team <teamname>
