### ISSUE TITLE
Error with job status

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/trailblazer#239] opened 2023-07-17 09:49 UTC
Trailblazer is faling when status in the job table is "canceled". This is fixed when changed to "cancelled".

Currently, status in the analysis table and the job table ARE NOT THE SAME and they accept different values.
```
class Analysis(Model):
  status = Column(types.Enum(*STATUS_OPTIONS))
('pending', 'running', 'completed', 'failed', 'error', 'canceled', 'completing', 'qc')
```

```
class Job(Model):
    status = Column(types.Enum(*JOB_STATUS_OPTIONS))
('completed', 'running', 'pending', 'completing', 'failed', 'cancelled', 'timeout')
```

Both lists are very similar but not identical.

Tower is currently using the same status values for both analysis and job tables and this leads to the error above. 

- Quick fix:  not allow `canceled` or `error` and return `failed` (status accepted by both tables) instead.

- Permanent fix: standarize status in both tables, as there are only few differences: cancelled/canceled, timeout, error, (qc). We should use `cancelled` instead of `canceled`

**Comment by fevac** [comment] 2023-08-07 14:29
@henrikstranneheim any objection against making the allowed values for Job Status the same as Analysis status?? that would require making some changes so values for SlurmJobStatus are converted to TrailblalzerStatus  prior storing in the sql database

**Comment by henrikstranneheim** [comment] 2023-08-08 07:22
> @henrikstranneheim any objection against making the allowed values for Job Status the same as Analysis status?? that would require making some changes so values for SlurmJobStatus are converted to TrailblalzerStatus prior storing in the sql database

I think that sounds like the way to go! @seallard If you have time - it would be great to fix this

**Comment by seallard** [comment] 2023-08-10 12:05
For the refinement:
- Do we need to transform the existing data in the status column to ensure all statuses are set to valid values?
- What should the new statuses be called?
- Do any other repos rely on any of these status fields and need to be updated as well?

**Comment by henrikstranneheim** [comment] 2023-08-30 12:28
> For the refinement:
> 
>     * Is there no semantic value in distinguishing the status for a job and an analysis? Are they always the same?

No I do not think so. Analysis can be a subset, but canceled should be fixed to cancelled.
> 
>     * What should the new status enum be called? TrailblazerStatus?

Yes, it already exist, together with SlurmJobStatus (for Jobs).
> 
>     * Do we need to transform the existing data in the status column to ensure all statuses are set to valid values according to the new enum?
> 
Yes, they should be aligned.

>     * Do any other repos rely on any of these status fields and need to be updated as well?

Might be in Cg and Cigrid

**Comment by fevac** [comment] 2023-08-31 07:14
Decision:

Separate in two PRs:
1. Higher prio:  Change `canceled` spelling to `cancelled`. Update databases. Update other repos if needed.

2. Lower prio: Keep TrailblazerStatus to keep track of the analysis status and create a TrailblazerJobStatus to keep track of jobs status, independently of slurm or tower. This require making a mapping with from slurm status to job status

**Comment by ChrOertlin** [comment] 2024-07-24 14:18
# Refinement

Closing this issue as the first part of the issue is solved.

Part 2: The status of an analysis could require different fields like QC which a job does not necessarily need to have. Standardising them therefore is perhaps not ideal.

**Closed by ChrOertlin** 2024-07-24 14:18 UTC
Labels: Bug, Urgency M, Urgency L
